/* eslint-disable no-useless-escape */
export const translater = {
    latcyr(string) {
      let car = String(string)
      car = car.replace(/YA/g, 'Я')
      car = car.replace(/YO/g, 'Ё')
      car = car.replace(/YU/g, 'Ю')
      car = car.replace(/TS/g, 'Ц')
      car = car.replace(/Ya/g, 'Я')
      car = car.replace(/Yo/g, 'Ё')
      car = car.replace(/Yu/g, 'Ю')
      car = car.replace(/Ts/g, 'Ц')
      car = car.replace(/ya/g, 'я')
      car = car.replace(/yo/g, 'ё')
      car = car.replace(/yu/g, 'ю')
      car = car.replace(/ts/g, 'ц')
  
      car = car.replace(/\n /g, '\n')
      car = car.replace(/G`/g, 'Ғ')
      car = car.replace(/g`/g, 'ғ')
      car = car.replace(/Gʻ/g, 'Ғ')
      car = car.replace(/gʻ/g, 'ғ')
      car = car.replace(/G'/g, 'Ғ')
      car = car.replace(/g'/g, 'ғ')
  
      car = car.replace(/O`/g, 'Ў')
      car = car.replace(/o`/g, 'ў')
      car = car.replace(/Oʻ/g, 'Ў')
      car = car.replace(/oʻ/g, 'ў')
      car = car.replace(/O'/g, 'Ў')
      car = car.replace(/o'/g, 'ў')
  
      car = car.replace(/\n/g, '\n ')
      car = car.replace(/,/g, ', ')
      car = car.replace(/:/g, ': ')
      car = car.replace(/;/g, '\? ')
      car = car.replace(/·/g, '\; ')
      car = car.replace(/\./g, '\. ')
      car = car.replace(/!/g, '! ')
      car = car.replace(/‘/g, 'ь')
      car = car.replace(/’/g, 'ь')
      car = car.replace(/\'/g, 'ь')
      car = car.replace(/ʻ/g, 'ь')
      car = car.replace(/ʻʻ/g, 'ъ')
  
      car = car.replace(/''/g, 'ъ') // var
      car = car.replace(/ʹʹ/g, 'ъ') // bon
  
      car = car.replace(/Shch/g, 'Щ')
      car = car.replace(/Sh/g, 'Ш')
      car = car.replace(/Ch/g, 'Ч')
      car = car.replace(/A/g, 'А')
      car = car.replace(/B/g, 'Б')
      car = car.replace(/H/g, 'Ҳ')
      car = car.replace(/D/g, 'Д')
      car = car.replace(/E/g, 'Е')
      car = car.replace(/F/g, 'Ф')
      car = car.replace(/G/g, 'Г')
      car = car.replace(/I/g, 'И')
      car = car.replace(/J/g, 'Ж')
      car = car.replace(/K/g, 'К')
      car = car.replace(/Q/g, 'Қ')
      car = car.replace(/L/g, 'Л')
      car = car.replace(/M/g, 'М')
      car = car.replace(/N/g, 'Н')
      car = car.replace(/O/g, 'О')
      car = car.replace(/P/g, 'П')
      car = car.replace(/R/g, 'Р')
      car = car.replace(/S/g, 'С')
      car = car.replace(/T/g, 'Т')
      car = car.replace(/U/g, 'У')
      car = car.replace(/V/g, 'В')
      car = car.replace(/X/g, 'Х')
      car = car.replace(/Y/g, 'Й')
      car = car.replace(/Z/g, 'З')
  
      car = car.replace(/shch/g, 'щ')
      car = car.replace(/sh/g, 'ш')
      car = car.replace(/ch/g, 'ч')
      car = car.replace(/h/g, 'ҳ')
      car = car.replace(/a/g, 'а')
      car = car.replace(/b/g, 'б')
      car = car.replace(/d/g, 'д')
      car = car.replace(/e/g, 'е')
      car = car.replace(/f/g, 'ф')
      car = car.replace(/g/g, 'г')
      car = car.replace(/i/g, 'и')
      car = car.replace(/j/g, 'ж')
      car = car.replace(/k/g, 'к')
      car = car.replace(/q/g, 'қ')
      car = car.replace(/l/g, 'л')
      car = car.replace(/m/g, 'м')
      car = car.replace(/n/g, 'н')
      car = car.replace(/o/g, 'о')
      car = car.replace(/p/g, 'п')
      car = car.replace(/r/g, 'р')
      car = car.replace(/s/g, 'с')
      car = car.replace(/t/g, 'т')
      car = car.replace(/u/g, 'у')
      car = car.replace(/v/g, 'в')
      car = car.replace(/x/g, 'х')
      car = car.replace(/y/g, 'й')
      car = car.replace(/z/g, 'з')
  
      return car
    },
  
    cyrlat(string) {
      let car = String(string)
  
      car = car.replace(/Ғ/g, 'Gʻ')
      car = car.replace(/ғ/g, 'gʻ')
  
      car = car.replace(/Щ/g, 'Shch')
      car = car.replace(/Ч/g, 'Ch')
      car = car.replace(/Ш/g, 'Sh')
      car = car.replace(/А/g, 'A')
      car = car.replace(/Б/g, 'B')
      car = car.replace(/Д/g, 'D')
      car = car.replace(/[ЕЭ]/g, 'E')
      car = car.replace(/Ф/g, 'F')
      car = car.replace(/Г/g, 'G')
      car = car.replace(/Ҳ/g, 'H')
      car = car.replace(/И/g, 'I')
      car = car.replace(/Ж/g, 'J')
      car = car.replace(/К/g, 'K')
      car = car.replace(/Қ/g, 'Q')
      car = car.replace(/Л/g, 'L')
      car = car.replace(/М/g, 'M')
      car = car.replace(/Н/g, 'N')
      car = car.replace(/О/g, 'O')
      car = car.replace(/П/g, 'P')
      car = car.replace(/Р/g, 'R')
      car = car.replace(/С/g, 'S')
      car = car.replace(/Т/g, 'T')
      car = car.replace(/У/g, 'U')
      car = car.replace(/В/g, 'V')
      car = car.replace(/Х/g, 'X')
      car = car.replace(/Й/g, 'J')
      car = car.replace(/Ы/g, 'Y')
      car = car.replace(/З/g, 'Z')
      car = car.replace(/Ъ/g, 'ʻʻ')
      car = car.replace(/Ь/g, 'ʻ')
  
      car = car.replace(/щ/g, 'shch')
      car = car.replace(/ч/g, 'ch')
      car = car.replace(/ш/g, 'sh')
      car = car.replace(/а/g, 'a')
      car = car.replace(/б/g, 'b')
      car = car.replace(/д/g, 'd')
      car = car.replace(/[еэ]/g, 'e')
      car = car.replace(/ф/g, 'f')
      car = car.replace(/г/g, 'g')
      car = car.replace(/ҳ/g, 'h')
      car = car.replace(/и/g, 'i')
      car = car.replace(/ж/g, 'j')
      car = car.replace(/к/g, 'k')
      car = car.replace(/қ/g, 'q')
      car = car.replace(/л/g, 'l')
      car = car.replace(/м/g, 'm')
      car = car.replace(/н/g, 'n')
      car = car.replace(/о/g, 'o')
      car = car.replace(/п/g, 'p')
      car = car.replace(/р/g, 'r')
      car = car.replace(/с/g, 's')
      car = car.replace(/т/g, 't')
      car = car.replace(/у/g, 'u')
      car = car.replace(/в/g, 'v')
      car = car.replace(/х/g, 'x')
      car = car.replace(/й/g, 'j')
      car = car.replace(/ы/g, 'y')
      car = car.replace(/з/g, 'z')
      car = car.replace(/ъ/g, 'ʻʻ')
      car = car.replace(/ь/g, 'ʻ')
  
      car = car.replace(/Я/g, 'Ya')
      car = car.replace(/Ё/g, 'Yo')
      car = car.replace(/Ю/g, 'Yu')
      car = car.replace(/Ц/g, 'Ts')
      car = car.replace(/Ў/g, 'Oʻ')
  
      car = car.replace(/я/g, 'ya')
      car = car.replace(/ё/g, 'yo')
      car = car.replace(/ю/g, 'yu')
      car = car.replace(/ц/g, 'ts')
      car = car.replace(/ў/g, 'oʻ')
  
      return car
    }
  }
  